# Generated by Django 3.0.8 on 2020-08-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200810_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='isOpen',
            field=models.BooleanField(default=True),
        ),
    ]
